### ISSUE TITLE
Latest version update breaks in `preinstall` task if package-lock is missing

### ISSUE THREAD

**Issue by easingthemes** [Netcentric/progux#24]
**Describe the bug**

`npm-force-resolutions` is aded in latest update.
This plugin requires package-lock to exists
This is not the case in all projects.

package-lock from this repo can not be used since it's ignored when package is published to npm.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create new directory.
2. Init npm project `npm  init -y`
3. Install progux `npm i @netcentric/progux`

```
progux-test $npm i @netcentric/progux

> @netcentric/progux@1.2.1 preinstall ~/progux-test/node_modules/@netcentric/progux
> npx npm-force-resolutions

npx: installed 6 in 2.619s
Error: ENOENT: no such file or directory, open './package-lock.json'
```

**Expected behavior**
Installs without error

**Comment by ines-akrap** [comment]
Solved in https://github.com/Netcentric/progux/pull/25
